markdown: redcarpet
highlighter: pygments
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: John connor
subTitle: "To be or not to be,that is the question..."
description: John,connor,John connor, acs1899, GitHub, Jekyll, Works, css, html, javascript。
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 文章分类
    url: 'javascript:void(0);'
  - text: 文章归档
    url: /archives.html
  - text: 关于
    url: /contact.html

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: https://plus.google.com/111953488722726761148/posts
  - class: fa-facebook
    url: https://www.facebook.com/wenqi.luo.12
  - class: fa-github
    url: https://github.com/acs1899
  - class: fa-weibo
    url: http://weibo.com/u/1308465790
  - class: fa-twitter
    url: https://twitter.com/Mashell81326713
  - class: fa-rss
    url: /atom.xml

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1

#评论信息
disqus:
  config: true
  id: acs1899blog

duoshuo:
  config: false
  id: acs1899blog
